### ISSUE TITLE
Shopify search bar showing articles that do not match with user query.

### ISSUE THREAD

**Issue by MilanGrujicic** [codedex-io/python-101#57] opened 2023-10-15 09:41 UTC
Hello team,

For the sake of my score, I will be opening an issue on /python-101 repo as I don't see any other repo this issue would fit.

### Description
On the [Codedex shop page](https://codedex.myshopify.com/), the search bar behaves in such a way that it displays products that do not match with what the user searched.

### Examples
- Searching for string "what", displays the item Notebook, which has nothing to do with what was searched. See picture shopify01.png. 👇
![shopify01](https://github.com/codedex-io/python-101/assets/48260426/b74f3aad-576b-4c54-8679-985f4c835096)

- Searching for int 1, displays the items Notebook and Women's Short Sleeve Tee, see picture shopify02.png. 👇
![shopify02](https://github.com/codedex-io/python-101/assets/48260426/643c407e-3b3a-4453-8402-123e0bc262c5)

Q: Is that a bug or a feature?

**Comment by sonnynomnom** [comment] 2023-10-19 01:33
This is not a bug on our end. It's Shopify's problem unfortunately! Closing this.

**Closed by sonnynomnom** 2023-10-19 01:33 UTC
